services:

    laravel.test:
        image: localhost:5000/php-ci:${DOCKER_IMAGE_TAG_CI}
        build:
            context: .
            dockerfile: ./infra/php/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - 'php-fpm-socket:/var/run/php-fpm/'
        networks:
            - sail
        depends_on:
            pgsql:
                condition: service_healthy
            # redis:
            #     condition: service_started
    nginx:
        image: localhost:5000/nginx-ci:${DOCKER_IMAGE_TAG_CI}
        build:
            context: ./infra/nginx
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        environment:
            WWWUSER: '${WWWUSER}'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './public:/usr/share/nginx/html/:ro'
            - 'php-fpm-socket:/var/run/php-fpm/'
        depends_on:
            - laravel.test
        networks:
            - sail
    pgsql:
        image: 'postgis/postgis:16-3.4'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './infra/postgres/20-create-testing-database.sql:/docker-entrypoint-initdb.d/20-create-testing-database.sql:ro'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    php-fpm-socket:
        driver: local
