#!/usr/bin/env sh
set -e

#/var/run/php-fpmのパーミッション表示
ls -la /var/run/php-fpm

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

# HACK: 強制的にマイグレーション
php artisan migrate --force

php artisan optimize

exec "$@"
