#!/usr/bin/env sh
set -e

if [ ! -z "$WWWUSER" ]; then
    echo  usermod -u $WWWUSER sail
    usermod -u $WWWUSER sail
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
