name: CD for PR
on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      head_ref: ${{ steps.vars.outputs.head_ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT && echo "head_ref=$(echo ${GITHUB_HEAD_REF} | sed -e 's/\//-/g')" >> $GITHUB_OUTPUT
  build:
    needs:
      - prepare
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
  ci:
    needs:
      - prepare
      - build
    uses: ./.github/workflows/test_backend.yml
    secrets: inherit
    with:
      docker_image_tag_ci: ${{ needs.build.outputs.docker_image_tag_ci }}
  image-scan:
    needs:
      - prepare
      - build
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
    with:
      docker_image_tag_ci: ${{ needs.build.outputs.docker_image_tag_ci }}
  # TODO
  # image-push:
  #   if: github.event.pull_request.draft == false
  #   uses: ./.github/workflows/push-to-ghcr.yml
  #   needs:
  #     - prepare
  #     - ci
  #   with:
  #     sha_short: ${{ needs.prepare.outputs.sha_short }}
  #     ref: ${{ needs.prepare.outputs.head_ref }}
  #   secrets: inherit
