on:
  workflow_call:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
        type: string
      infra_ref:
        description: "Infrastructure reference"
        default: "main"
        type: string
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      infra_ref:
        description: "Infrastructure reference"
        default: "main"
        type: string

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup kubectl
        uses: azure/setup-kubectl@v3.2
      - name: Create Kubernetes config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > /tmp/kube_config
      - name: Install or upgrade applications
        run: |
          envsubst < .github/applicationset.template.yaml | kubectl apply -n argocd -f -
        env:
          ENV: main
          TAG: ${{ inputs.tag_name }}
          INFRA_REF: ${{ inputs.infra_ref }}
          KUBECONFIG: /tmp/kube_config
          APP_KEY: ${{ secrets.APP_KEY }}
