on:
  workflow_call:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
      - name: Login to ArgoCD
        run: |
          argocd login --insecure --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web ${{ secrets.ARGOCD_SERVER }}
      - name: Update parameters
        run: |
          argocd app set app-main -p laravel.image.tag=${{ inputs.tag_name }}
      - name: Sync
        run: |
          argocd app sync app-main
