on:
  workflow_call:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: okteto/okteto:2.24.1
    steps:
    - name: Generate github token
      id: generate_token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ vars.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: miso-memoReal/memorial-infra
        token: ${{ steps.generate_token.outputs.token }}
    - name: "Deploy the preview environment"
      run: |
        okteto context use --token=${{ secrets.OKTETO_TOKEN }}
        eval okteto kubeconfig
        helm upgrade --install memorial-na2na-p backend/k8s/charts --set nginx.image.tag=${TAG_NAME} --set laravel.image.tag=${TAG_NAME}
      env:
        TAG_NAME: ${{ inputs.tag_name }}
