name: Image Scan
on:
  workflow_call:
    inputs:
      docker_image_tag_ci:
        required: true
        type: string
    secrets: {}

env:
  COMPOSE_FILE: compose.ci.yml

jobs:
  build:
    name: Image Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Docker Registry
        uses: actions/cache@v3
        with:
          path: /tmp/docker-registry
          key: docker-registry-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            docker-registry-${{ github.ref }}
            docker-registry-
      - name: Boot-up Local Docker Registry
        run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2
      - name: Wait for Docker Registry
        run: npx wait-on tcp:5000
      - name: Get Docker Image Tag
        env:
          TAG: ${{ inputs.docker_image_tag_ci }}
        run: |
          echo "DOCKER_IMAGE_TAG_CI=$TAG" >> $GITHUB_ENV
          echo TAG $TAG
      - name: Docker Compose Pull
        run: |
          docker compose pull laravel.test postgres
      - name: Nginx Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "memorial-backend-nginx:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      - name: PHP Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "memorial-backend-laravel.test:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
