name: Image Push
on:
  workflow_call:
    inputs:
      docker_image_tag_ci:
        required: true
        type: string
      sha_short:
        description: 'short sha of commit to deploy'
        type: string
        required: true
      branch:
        description: 'branch name to deploy'
        type: string
        required: true
    secrets: {}

env:
  COMPOSE_FILE: compose.ci.yml

jobs:
  push:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare Docker Image
        uses: ./.github/actions/prepare-docker-image
        with:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Pull from local registry
        run: |
          docker compose -f ${{ env.COMPOSE_FILE }} pull laravel.test nginx
      - name: List local images
        run: |
          docker images
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NA2NA_ID }}
          password: ${{ secrets.DOCKER_HUB_NA2NA_PASSWORD }}
      - name: Push to registry
        run: |
          docker tag localhost:5000/php-ci:${{ inputs.docker_image_tag_ci }} ghcr.io/${{ steps.prepare.outputs.name }}-php:${{ inputs.sha_short }}
          docker tag localhost:5000/nginx-ci:${{ inputs.docker_image_tag_ci }} ghcr.io/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.sha_short }}
          docker tag localhost:5000/php-ci:${{ inputs.docker_image_tag_ci }} ghcr.io/${{ steps.prepare.outputs.name }}-php:${{ inputs.branch }}
          docker tag localhost:5000/nginx-ci:${{ inputs.docker_image_tag_ci }} ghcr.io/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.branch }}
          docker tag localhost:5000/php-ci:${{ inputs.docker_image_tag_ci }} na2na/${{ steps.prepare.outputs.name }}-php:${{ inputs.sha_short }}
          docker tag localhost:5000/nginx-ci:${{ inputs.docker_image_tag_ci }} na2na/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.sha_short }}
          docker tag localhost:5000/php-ci:${{ inputs.docker_image_tag_ci }} na2na/${{ steps.prepare.outputs.name }}-php:${{ inputs.branch }}
          docker tag localhost:5000/nginx-ci:${{ inputs.docker_image_tag_ci }} na2na/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.branch }}
          docker push ghcr.io/${{ steps.prepare.outputs.name }}-php:${{ inputs.sha_short }}
          docker push ghcr.io/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.sha_short }}
          docker push ghcr.io/${{ steps.prepare.outputs.name }}-php:${{ inputs.branch }}
          docker push ghcr.io/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.branch }}
          docker push na2na/${{ steps.prepare.outputs.name }}-php:${{ inputs.sha_short }}
          docker push na2na/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.sha_short }}
          docker push na2na/${{ steps.prepare.outputs.name }}-php:${{ inputs.branch }}
          docker push na2na/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.branch }}
