name: Remove Images
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch name to deploy'
        type: string
        required: true

jobs:
  remove-images:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
          echo "OWNER_REPO=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Remove images from GHCR
        run: |
          GHCR_IMAGE_PHP="ghcr.io/${{ steps.prepare.outputs.name }}-php:${{ inputs.branch }}"
          GHCR_IMAGE_NGINX="ghcr.io/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.branch }}"
          echo "Deleting $GHCR_IMAGE_PHP and $GHCR_IMAGE_NGINX from GHCR..."
          curl -X DELETE -u ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} "https://ghcr.io/v2/${{ steps.prepare.outputs.name }}-php/manifests/${{ inputs.branch }}"
          curl -X DELETE -u ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} "https://ghcr.io/v2/${{ steps.prepare.outputs.name }}-nginx/manifests/${{ inputs.branch }}"
      - name: Remove images from Docker Hub
        run: |
          DOCKER_HUB_IMAGE_PHP="na2na/${{ steps.prepare.outputs.name }}-php:${{ inputs.branch }}"
          DOCKER_HUB_IMAGE_NGINX="na2na/${{ steps.prepare.outputs.name }}-nginx:${{ inputs.branch }}"
          echo "Deleting $DOCKER_HUB_IMAGE_PHP and $DOCKER_HUB_IMAGE_NGINX from Docker Hub..."
          docker_hub_token=$(curl -s -X POST -H "Content-Type: application/json" \
          -d '{"username": "'${{ secrets.DOCKER_HUB_NA2NA_ID }}'", "password": "'${{ secrets.DOCKER_HUB_NA2NA_PASSWORD }}'"}' \
          https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE -H "Authorization: JWT $docker_hub_token" "https://hub.docker.com/v2/repositories/na2na/${{ steps.prepare.outputs.name }}-php/tags/${{ inputs.branch }}"
          curl -X DELETE -H "Authorization: JWT $docker_hub_token" "https://hub.docker.com/v2/repositories/na2na/${{ steps.prepare.outputs.name }}-nginx/tags/${{ inputs.branch }}"
