name: Remove Images
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch name to deploy'
        type: string
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
          echo "OWNER_REPO=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "tagName=$(echo ${{ inputs.branch }} | tr '/' '-')" >> $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.prepare.outputs.name }}
      lower_owner_repo: ${{ steps.prepare.outputs.OWNER_REPO }}
      tagName: ${{ steps.prepare.outputs.tagName }}
  remove-docker-hub-images:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Remove images from Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_NA2NA_ID }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_NA2NA_PASSWORD }}
        run: |
          DOCKER_HUB_IMAGE_PHP="na2na/${{ needs.prepare.outputs.name }}-php:${{ needs.prepare.outputs.tagName }}"
          DOCKER_HUB_IMAGE_NGINX="na2na/${{ needs.prepare.outputs.name }}-nginx:${{ needs.prepare.outputs.tagName }}"
          echo "Deleting $DOCKER_HUB_IMAGE_PHP and $DOCKER_HUB_IMAGE_NGINX from Docker Hub..."
          docker_hub_token=$(curl -s -X POST -H "Content-Type: application/json" \
          -d '{"username": "'"$DOCKER_HUB_USERNAME"'", "password": "'"$DOCKER_HUB_PASSWORD"'"}' \
          https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE -H "Authorization: JWT $docker_hub_token" "https://hub.docker.com/v2/repositories/na2na/${{ needs.prepare.outputs.name }}-php/tags/${{ needs.prepare.outputs.tagName }}"
          curl -X DELETE -H "Authorization: JWT $docker_hub_token" "https://hub.docker.com/v2/repositories/na2na/${{ needs.prepare.outputs.name }}-nginx/tags/${{ needs.prepare.outputs.tagName }}"
  remove-ghcr-images-php:
    needs: prepare
    uses: ./.github/workflows/remove-ghcr-image.yml
    with:
      package-name: ${{ needs.prepare.outputs.name }}-php
      tag-name: ${{ needs.prepare.outputs.tagName }}
    secrets: inherit
  remove-ghcr-images-nginx:
    needs: prepare
    uses: ./.github/workflows/remove-ghcr-image.yml
    with:
      package-name: ${{ needs.prepare.outputs.name }}-nginx
      tag-name: ${{ needs.prepare.outputs.tagName }}
    secrets: inherit
