name: Remove Package Version
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      tag-name:
        required: true
        type: string

jobs:
  remove-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      - name: Get package version ID
        id: get_package_version_id
        run: |
          response=$(gh api users/${{ github.repository_owner }}/packages/container/${{ inputs.package-name }}/versions)
          package_version_id=$(echo "$response" | jq -r '.[] | select(.metadata.container.tags[] == "${{ inputs.tag-name }}").id')
          echo "PACKAGE_VERSION_ID=$package_version_id" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete package version
        if: steps.get_package_version_id.outputs.PACKAGE_VERSION_ID != null
        run: |
          echo "Deleting package version ${{ steps.get_package_version_id.outputs.PACKAGE_VERSION_ID }}..."
          gh api -X DELETE /orgs/${{ github.repository_owner }}/packages/container/${{ inputs.package-name }}/versions/${{ steps.get_package_version_id.outputs.PACKAGE_VERSION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
