name: Test(Backend)
on:
  workflow_call:
    inputs:
      docker_image_tag_ci:
        required: true
        type: string
    secrets: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker Image
        uses: ./.github/actions/prepare-docker-image
        with:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Prepare for envfiles
        run: |
          cp .env.example .env
          cp compose.ci.yml docker-compose.yml
      - name: Docker Compose Up
        run: |
          docker compose up -d
        env:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Componser Install
        run: make composer-install
      - name: Test
        run: make test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker Image
        uses: ./.github/actions/prepare-docker-image
        with:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Prepare for envfiles
        run: |
          cp .env.example .env
          cp compose.ci.yml docker-compose.yml
      - name: Docker Compose Up
        run: |
          docker compose up -d
        env:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Componser Install
        run: make composer-install
      - name: Lint
        run: make lint
