name: Test(Backend)
on:
  workflow_call:
    inputs:
      docker_image_tag_ci:
        required: true
        type: string
    secrets: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker Image
        uses: ./.github/actions/prepare-docker-image
        with:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Setup CI
        run: make setup-ci
      - name: Test
        run: make test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker Image
        uses: ./.github/actions/prepare-docker-image
        with:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Setup CI
        run: make setup-ci
      - name: Lint
        run: make lint
