name: Test(Backend)
on: workflow_call

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CI
        run: make setup
      - name: Test
        run: make test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CI
        run: make setup
      - name: Lint
        run: make lint
